# Generated by Django 2.1.5 on 2023-03-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_news', '0003_auto_20230321_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('author', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('text', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
